```{r, include=FALSE}
# Set up template page per organisation
org_summary <- list()
#  --- Filter data to organisation
org_summary$data <- map(summary$data,
                   ~ .x |> filter(organisation == meta_params$organisation))
# --- print-ready tables
org_summary$tables <- summary$tables[[meta_params$organisation]]
# overall data
key_insights_data <- map(org_summary$data,
                        ~ .x |> filter(strata == "overall"))

# Create key insights text
key_text <- generate_key_insights(key_insights_data$latest)
meta_params$strata <- "sex"
```

## row 1 {height="15%"}

```{r}
value_box(
  title = "Participants",
  value = key_text$n_id,
  p(key_text$n_followup, "participants continuing to report after baseline"),
  showcase = bs_icon("clipboard"),
  theme = "teal"
)
```

```{r}
value_box(
  title = "Typical loss of bodyweight from pre-war",
  value = key_text[["weight_change_percent_prewar"]],
  p("Median and interquartile range (25%-75% of participants), from pre-war to latest measurement"),
  showcase = bs_icon("activity"),
  theme = "teal"
)
```

```{r}
value_box(
  title = "% clinically underweight",
  value = key_text[["bmi_category_daily_Underweight"]],
  p("WHO"),
  showcase = bs_icon("activity"),
  theme = "teal"
)
```

## row 2 {height="40%"}

::: {.panel-tabset title="Participation"}

### Participants
```{r}
#| fill: false
#| out-width: "100%"
#| fig-align: center
plot_participants_over_time(key_insights_data$timeseries) |> 
  ggplotly()|> 
  layout(legend = list(orientation = 'h'))
markdown("<details> <summary> About the data </summary> 
         Daily participation from newly recruited participants (light green), or repeat measurements from returning participants (dark blue); with cumulative number of unique participants over time (shaded grey area) and their unique measurements (grey line). </details>")
```

### Demographics
```{r}
#| fill: false
org_summary$tables$demographic_strata
```

### Data
```{r}
#| fill: false
org_summary$tables$data_quality
```

:::

```{r}
#| title: "Change in BMI classification"
org_summary$tables$bmi_crosstab
markdown("<details> <summary> About the data </summary> 
Prevalence of body mass index (BMI) classifications among participants, calculated from self-reported weight before October 2023 (pre-war), and latest measurement during study period (from July 2025). Adult BMI classifications are underweight (under 18.5 kg/m2), normal weight (18.5 to 24.9), overweight (25 to 29.9), and obese (30 or more). </details>")
```

## row 3 {height="45%}

## ...still row 3

::: {.panel-tabset}

### Trends 

```{r}
meta_params$strata <- "overall"
```

{{< include _tab-strata.qmd >}}

### Sex
```{r}
meta_params$strata <- "sex"
```

{{< include _tab-strata.qmd >}}

### Age
```{r}
meta_params$strata <- "age"
```

{{< include _tab-strata.qmd >}}

:::
