project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Monitoring the nutritional status of humanitarian workers in Gaza"
  navbar:
    right:
      - icon: house
        text: " "
        href: index.qmd
      - icon: question-circle
        menu:
          - text: About the project
            href: about.qmd
          - text: Study protocol
            href: protocol.qmd
          - text: Report an issue
            href: https://github.com/cmmid/gaza-response/issues/new
      - icon: translate
        menu:
          - text: English
            href: index.qmd
          - text: Arabic
            href: arabic.qmd
      - icon: github
        href:  https://github.com/cmmid/gaza-response
  comments:
    giscus:
      repo: cmmid/gaza-response
      loading: lazy
      input-position: top
      mapping: 11

  body-footer: <script data-goatcounter="https://gaza-response.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



