project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Gaza response: Monitoring the nutritional status of humanitarian workers"
  navbar:
    right:
      - icon: house
        text: Home
        href: index.qmd
      - icon: question-circle
        text: About
        menu:
          - text: About the project
            href: about.qmd
          - text: Study protocol
            href: protocol.qmd
          - text: Report an issue
            href: https://github.com/cmmid/gaza-response/issues/new
      - icon: github
        href:  https://github.com/cmmid/gaza-response
      - icon: translate
        menu:
          - text: English
            href: index.qmd
          - text: Arabic
            href: arabic.qmd
  body-footer: <script data-goatcounter="https://gaza-response.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



