project:
  type: website
  render:
   - "*.qmd"

website:
  title: "Monitoring the nutritional status of humanitarian workers in Gaza"
  navbar:
    right:
      - icon: house
        text: " "
        href: index.qmd
      - icon: question-circle
        menu:
          - text: About the project
            href: about.qmd
          - text: Study protocol
            href: protocol.qmd
          - text: Contact
            href: contact.qmd
      - icon: translate
        menu:
          - text: English
            href: index.qmd
          - text: Arabic
            href: arabic.qmd
      - icon: github
        href:  https://github.com/cmmid/gaza-response
  announcement:
    icon: cone-striped
    dismissable: true
    position: below-navbar
    content: "**Active development:** We are actively collecting data and developing this resource. [Find out more](./about) and [get involved](./contact)"
    type: warning
  site_url: "https://cmmid.github.io/gaza-response/"
  open-graph: true
  body-footer: <script data-goatcounter="https://gaza-response.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


