---
format: 
  dashboard:
    orientation: columns
    scrolling: false
    include-in-header:
      text: |
            <script src="lshtm.js"></script>
    css: "styles.css"
    fig-format: svg
toc: false
execute: 
  echo: false
  cache: false
---

```{r, include=FALSE}
# Set up template page per organisation
pacman::p_load(here, 
               purrr, readr, dplyr, forcats, stringr,
               bslib, bsicons,
               ggplot2, plotly, shiny, patchwork)
source(here("R", "data-analysis/ggplot_theme.R"))
if (is.null(meta_params$organisation) | length(meta_params$organisation) > 1) {
  meta_params$organisation <- "Overall"}

# Get relevant data
# --- across full cohort (latest record for each ppt)
summary_all_org <- summary_all[[meta_params$organisation]]
# --- at daily intervals (participants recorded each day)
summary_daily_org <- summary_daily[[meta_params$organisation]]
# --- print-ready tables
summary_tables_org <- summary_tables[[meta_params$organisation]]
```

## ROW OF TABS {.tabset}

### Key insights

{{< include ./quarto/_tab-key-insights.qmd >}}

<!--- new tab ------------------------------------------------------------>
### Trends by demographic {.tabset}

#### Overall

```{r, include=FALSE}
meta_params$stratum <- "overall"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Sex

```{r, include=FALSE}
meta_params$stratum <- "sex"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Age

```{r, include=FALSE}
meta_params$stratum <- "age"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Dependent children^[number of dependent children]

```{r, include=FALSE}
meta_params$stratum <- "children_feeding"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Role

```{r, include=FALSE}
meta_params$stratum <- "role"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Governorate

```{r, include=FALSE}
meta_params$stratum <- "governorate"
```

{{< include ./quarto/_tab-demographic.qmd >}}


<!--- new tab ------------------------------------------------------------>
### Participation

{{< include ./quarto/_tab-participation.qmd >}}

