---
title: "Study protocol"
---

Version: 28 July 2025

Author: Francesco Checchi (LSHTM)

# Data collection and analysis

## Eligibility

All staff working for the organisation are eligible to take part in data collection. This includes expatriate, national (with a contract), daily worker/occasional staff and regular volunteers, if any.

## Data structure

The dataset will be **longitudinal**, meaning that multiple weight measures will be collected for the same individuals, with a unique ID linking sequential observations to each individual (staff member). This is far preferable in terms of statistical analysis to collecting observations that cannot be linked over time.

## Requirements

The LSHTM has prepared a **generic ODK/Kobo data collection platform** that any organisation can adopt. This should work on any Android mobile phone, tablet or computer. It will not work on Apple devices. Staff can toggle between identical Arabic and English versions of the data collection instruments.

Accordingly, **when they first join the system**, staff members will read the **information sheet**, provide **consent** (see Appendix), create a user ID (see below) and fill a brief **baseline questionnaire**: staff members will use a URL linking to the data collection screen for this one-off data collection. Staff need to be online when accessing this first URL on their browser. Even if they lose connectivity, the platform will allow them to complete the consent process and questionnaire and click submit: their submission will be queued and will be uploaded by their device when next connected to the internet.

They will also be provided with a separate URL that they will need to use each time they wish to record **new weight observations** for themselves or a colleague. Again, the first time they use the URL on their device, they will need to be online. Subsequently, they can be offline, and the data will be uploaded when the device next has an internet connection; it is also possible to close the browser tab after submitting data.

If staff delete their cookies or browsing history, it may be that they will once again need to be online when accessing either URL. However, they should not worry about losing data: this can only happen if the device is lost or breaks before uploading the latest weight observation. Even in these cases, data previously uploaded will be safe.

## Variables collected

**Baseline data collection:**

- Unique ID, specified once by each new participant: participants will be given two options for this: (i) specify their Palestinian national ID; (ii) specify the first initials of their name, father’s name and last name (e.g. Fatima Abdelwahab Salman) and their date of birth (dd/mm/yy, e.g. 03/11/1978), which in the above example will generate the following ID: FAS031178. If they choose option (ii), they will be reminded by the system to remember their ID.
- Date \[automatic\]
- Age \[16-99y\]
- Sex \[M, F, other/prefer not to say?\]
- Governorate where you currently live \[North Gaza, Gaza City, Deir al Balah, Rafah, Khan Younis\]
- Role \[expatriate staff, national staff / contracted, national staff / daily worker, other, prefer not to say\]
- Estimated height in cm \[100-230\]
- Estimated weight before the war started in Kg, to nearest decimal \[30.0 to 180.0\]
- Weight today in Kg, to nearest decimal \[30.0 to 180.0\]

**Ongoing data collection:**

- Unique ID, as above
- Date \[automatic\]
- Weight today in Kg, to nearest decimal \[30.0 to 180.0\]

## Analysis and publication

An **automated data pipeline** will be set, whereby data will be automatically captured from the server at daily intervals, pre-processed to remove implausible variables, and analysed to generate the following **aggregate visualisations**:

- Mean, median and inter-quartile range absolute and percent reduction in weight and body mass index (BMI) from pre-war baseline.
- Proportion of staff with BMI in different WHO categories: underweight <18.5, normal 18.50 – 24.99, overweight ≥ 25, obese ≥ 30.
- Trends in the mean, median and inter-quartile range weight, BMI and percent weight change, by date.
- Modelled percent change in individual weight, based on an additive growth model.

Visualisations will be available for the entire group of staff being monitored, but also according to the following stratifications: (i) by sex, (ii) by age group (<30yo, 30-44yo, 45+yo), (iii) by governorate of current residence, (iv) by staff role (any categories available).

All visualisations will be automatically updated on a publicly available **dashboard**.

## Confidentiality provisions

The following confidentiality provisions are built into the system:

- Data will be uploaded onto an **LSHTM secure server** that is compliant with UK Data Protection legislation and is being used for other sensitive studies, including storage of non-anonymised data;
- The **unique ID** specified by each participant, whichever option they choose, will be **encrypted** at source, meaning that the variable as uploaded onto the cloud will not be either the Palestinian ID or the initials-date of birth composite ID, but rather a (randomly generated) code that the LSHTM will not be able to decrypt;
- As no names or other uniquely identifiable variables are requested, data will be entirely **anonymised**;
- The public dashboard will enable members of the public to download graphs/tables as images, but will not enable any access to the original source data.

## Ethics

The system may be considered part of routine monitoring for the purpose of occupational health and humanitarian advocacy: as such, it should be exempt from institutional ethics review. However, the LSHTM has applied for ethics approval so as to cover the likely eventuality that data from the system are subjected to additional statistical analyses and submitted for scientific publication.

# Procedures

## Before system launch

The following need to be in place:

- a calibrated adult weight scale in a visible location (e.g. tea room) within each office or building to which staff typically report at least once a day.
- a designated staff member in each of the above locations, trained to calibrate the scale (if not electronic).
- a designated member of staff who can answer questions by staff on the system, including data protection aspects.

## Procedures for system launch

When the system is launched, the following procedures should be followed:

- all staff should be informed about the system through suitable means (e.g. at morning briefings; through email, Whatsapp groups etc.); this information should be reiterated at least twice over the subsequent week; the links to the two ODK data collection screens (consent + baseline questionnaire; ongoing weight observations) should be shared at this stage.
- key information to emphasise to staff (see also Information Sheet below) includes the following:
  - this initiative is meant to give a voice to the lived experience of staff who are facing starvation, and make this information available publicly for advocacy and war crimes investigation purposes.
  - hopefully other organisations will see the system and encourage their staff to join it.
  - taking part in data collection is completely up to each staff member; there will be no monitoring of who is providing data or not, and not providing data will not change anything for staff. It might be helpful if expatriate staff also join data collection.
  - staff can enter data on their mobile, their computer, or even someone else’s mobile/computer; they can use a different device on any given day; they just need the same ODK links; the first time they use either the first or second link, they will need to be online; thereafter, they can also be offline.
  - data entry should only take a few seconds; it would be great if staff enter their weight every day, but as often as possible would be good too. As soon as the device has an internet connection, the data will be automatically uploaded. Therefore, staff should take their weight and make sure to enter the information straight away, rather than trying to remember the number for later.
  - all the information will be anonymised and encrypted at the point of data entry, so that it will not be possible for anyone to identify staff from the data they provide.
  - we will generate analyses from everyone’s data and publish them automatically online, but also share these with the staff, so that you can also monitoring the evolution of the situation.
  - weight scales have been provided at each workplace \[specify where / who can direct staff at each workplace\]. If you have any questions about the system, please contact \[specify whom\].

## Procedures after system launch

After the system is launched:

- check regularly (at least once daily) that the weight balances are functional and (if manual) well-calibrated.
- remind staff once a week to enter their data and encourage any new employees to join the system.
- make sure that, for those who don’t have internet access, at least some of the key graphs showing trends are printed or otherwise shared.
- If there are any concerns from staff or other problems with the system, please email [Zeina.Jamaluddine@lshtm.ac.uk](mailto:Zeina.Jamaluddine@lshtm.ac.uk) cc [Francesco.Checchi@lshtm.ac.uk](mailto:Francesco.Checchi@lshtm.ac.uk) .

# Appendix: Information sheet and online consent statement

## Participant informant sheet

**Version:** 28 July 2025

**Title of the Project:** Monitoring the nutritional status of humanitarian workers in Gaza

**Introduction**

You are invited to take part in a project to monitor the nutritional situation of Save the Children (SCI)’s humanitarian workers in Gaza. Participation is entirely voluntary. Before you decide, it's important to understand why the project is being done and what it involves. Please review this information carefully. Feel free to ask anything that is unclear, talk to others if you wish, and take your time to decide.

**Who is organising and funding this study?**

The project is implemented by SCI with the support of the London School of Hygiene and Tropical Medicine (LSHTM), a university in the United Kingdom. There is no specific funding source for this study.

**What is the purpose of this study?**

This study aims to monitor the nutritional status of SCI staff currently working in Gaza by tracking their weight. The aim of this project is to give a voice to aid workers who are currently based in Gaza, as essentials and humanitarian aid continues to be blocked from entering Gaza.

**Why have you been asked to take part?**

You are being invited to take part in this project because you are currently working for SCI in Gaza.

**Do you have to take part?**

No. Participation is entirely voluntary and will not affect your employment or your rights as a staff member. To take part, you need to actively opt in. Your employer will not know whether you opted in or opted out.

**What will happen to me if I take part?**

If you agree to participate, you will be asked to complete a very short questionnaire with basic information on yourself. You will then be asked to log your weight on a daily basis, or as often as you can. Only electronic data will be collected. Data can be entered via phone or computer, even when you are offline. Although daily entries are not required, they are recommended to help track changes over time. Recording and entering your weight should take about a minute.

**What are the possible benefits of taking part?**

There are no direct benefits to you from taking part in this project. However, the findings are likely to be used by SCI and others to take decisions on nutrition and food security strategies, and to advocate for improved access to humanitarian assistance across Gaza. They may be used in the future to investigate war crimes.

**What are the possible risks and disadvantages?**

We do not expect you to experience any risks or disadvantages from participating in this project. However, if you have any questions or concerns about this project, please feel free to contact SCI focal point. If you remain unhappy and wish to complain formally, you can do this by contacting &lt;SCI contact for staff complaints&gt;.

**What will happen with your data?**

Once you submit data, these will be uploaded to the internet as soon as the device has an internet connection. LSHTM researchers will analyse the data and produce graphs and tables to describe the evolution of the nutritional situation of SCI’s staff. Each time new data are uploaded, the graphs and tables will be updated on a public online dashboard, which you can also access. This dashboard will only show group-level summaries, for example averages by job role, gender, age, or area of residence. It will not show individual data or allow individual data to be downloaded from the dashboard.

The data you provide might also be used by your organization and others to support decision-making around nutrition, food assistance, and humanitarian response. Researchers may also analyse and publish the anonymized data to better understand the nutritional situation in Gaza, including by estimating how much food was actually available to the population. These findings may be published in reports or scientific articles.

**Confidentiality**

The system only generates completely anonymised data, meaning it will not be possible from the dataset to identify your records or identity. You will need to create an ID when you first log into the system, but this ID will be encrypted before it is uploaded. Please keep a record of your ID, as you will need it each time you log your weight. Data will be stored on a secure cloud server at the LSHTM, which only designated LSHTM researchers have access to. No identifying information will ever be used in publications or shared outside the research team.

**Can I change my mind about taking part?**

Yes: if you do not wish to continue providing information to the system, you can simply stop entering data without any repercussions. If you would like your data to be fully deleted, you can contact the designated focal point (see below) with your username, and your data will be permanently removed from the system. This is entirely up to you.

**How will we use information about you after the project ends?**

The fully anonymised data may be made available online subsequent to SCI’s approval, and will be stored on the LSHTM server for up to 10 years, then deleted.

**Who should I contact for further information?**

If you would like any further information, please contact \[SCI focal point\] who can answer any questions you might have.

## Consent statement

**Title of the Project:** Monitoring the nutritional status of humanitarian workers in Gaza

Thank you for considering taking part in this data collection system. If you have any questions arising from the information sheet or explanation given to you, please contact \[SCI focal point\] and ask your questions before you decide whether to provide consent.  

| Statement | Yes/No |
| --- | --- |
| I have read the information sheet dated 27<sup>th</sup> of July 2025 for this study and I have or can access a copy of it if needed. |     |
| I understand that my consent is voluntary and that I am free to withdraw this consent at any time without giving any reason and without my job or legal rights being affected. |     |
| I understand that results from the study may be published in scientific journals or reports, without the use of any information that could identify me. |     |
| I agree to take part in this study |     |
