---
format: 
  dashboard:
    orientation: rows
    scrolling: false
    css: "./styles.css"
    fig-format: svg
    anchor-sections: true
lightbox: true
execute: 
  echo: false
  cache: true
---
```{r include=FALSE} 
# Set up BMI data
bmi_category <- data_filtered_current |> 
   group_by(group, label) |> 
   filter(grepl("bmi_category", variable)) |> 
   mutate(variable = str_remove_all(variable, "bmi_category_")) |> 
   separate(variable, into = c("timepoint", "bmi_category")) |> 
   mutate(bmi_category = na_if(bmi_category, "NA"),
          timepoint = if_else(timepoint == "prewar", 
                              "Autumn_2023", "Summer_2025")) 
# set up crosstalk for BMI categories -------------------
bmi_category_shared <- bmi_category |> 
   filter(stat == "percent") |> 
   highlight_key(group = "group")
# change in % "underweight" -----------------------------
# the change in % of each strata classified as underweight compared to prewar, eg +10% of males
 underweight_change <- pull(
   bmi_category |> 
      pivot_wider(names_from = "timepoint", values_from = "value") |> 
      filter(bmi_category == "underweight" & stat == "percent") |> 
      mutate(bmi_category_change = Summer_2025 - Autumn_2023),
   bmi_category_change, name = label)
```

```{r}
#| content: "card-sidebar"
markdown("Summary of most recent data provided by participants reporting over the last 3 days.
Current weight in kilograms (kg) and BMI (body mass index), in addition to percent change in weight and BMI from pre-war levels (before October 8th 2023). 
Negative values of percent change indicate weight loss, i.e. ‘-20%’ indicates an average loss of 20% of weight or BMI.")
group_filter <- crosstalk::filter_select(
   "filter", "Demographic",
   bmi_category_shared, ~group, multiple = F)
group_filter
```

```{r}
#| title: "BMI status"
plot_bmi <- plot_ly(data = bmi_category_shared,
        x = ~timepoint,
        y = ~value,
        color = ~bmi_category,
        stroke = ~timepoint,
        type = "bar",
        text = ~bmi_category,
        textposition = "none") |> 
   layout(barmode = "label")
shiny::tags$div(class = 'flexbox',
                shiny::tags$br(), 
                plot_bmi)
```
