---
format: 
  dashboard:
    orientation: rows
    scrolling: false
    css: "./styles.css"
    fig-format: svg
    anchor-sections: true
lightbox: true
execute: 
  echo: false
  cache: true
---
<!-- Organisation-level data -->
```{r include=FALSE}
data_filtered <- filter(data, organisation == params_meta$organisation)

data_filtered_current <- filter(data_filtered, 
                                !is.na(current_summary_date)) |> 
   mutate(date = current_summary_date)
# data_filtered <- recode_data_table(data_filtered)
```

<!-- Content ----------------------------------------------------------------->

## ROW 1

<!----------------------------->

### Current status {.tabset}

#### Key insights
```{r}
#params <- generate_key_insights(data_filtered_current, strata = "overall")
markdown("children_feeding")
```

#### BMI

{{< include quarto/_bmi.qmd >}}

#### Weight

{{< include quarto/_weight.qmd >}}

<!----------------------------->

### Participation {.tabset}

{{< include quarto/_participants.qmd >}}

<!-------------------------------------------------------------------->

## ROW 2 {.tabset}

```{r}
#| content: card-sidebar
group_filter <- crosstalk::filter_select(
   "filter", "Demographic",
   bmi_category_shared, ~group, multiple = F)
group_filter
```

#### BMI over time
```{r}
print("d")
```

#### Weight over time
```{r}
print("e")
```

<!------------------------- javascript to set the default plot to Overall -->
```{js}
$(document).ready(function() {
    document.getElementById("filter").getElementsByClassName("selectized")[0].selectize.setValue("overall", false);
    document.getElementById("checkbox").getElementsByClassName("selectized")[0].selectize.setValue("Summer_2025", false);
});
```
