
<h2 style="color: #2c3e50; margin-bottom: 1rem;">
  Participants
</h2>

The below chart shows data collected from participants over time, separated into new joiners and returning participants. The stacked bars indicate the weekly totals by participant type, and the grey line shows the cumulative number of participants over time.

```{r}
#| fill: false
#| fig-align: center
#| fig-subcap: "<details><summary>About the data</summary>Participation from newly recruited participants (light green), or repeat measurements from returning participants (dark blue); with cumulative number of unique participants over time (shaded grey area) and their unique measurements (grey line).</details>"
plot_participants_over_time(key_insights_data$timeseries) |> 
  ggplotly() |> 
  layout(legend = list(orientation = 'h'))
```

<h2 style="color: #2c3e50; margin-bottom: 1rem;">
  Demographics
</h2>


```{r}
#| fill: false
org_summary$tables$demographic_strata
```

<h2 style="color: #2c3e50; margin-bottom: 1rem;">
  Data
</h2>


```{r}
#| fill: false
org_summary$tables$data_quality
```



