---
format: 
  dashboard:
    orientation: rows
    scrolling: false
    css: "./styles.css"
    fig-format: svg
    anchor-sections: true
lightbox: true
execute: 
  echo: false
  cache: true
---
#### Participation
```{r}
#| content: "card-sidebar"
markdown("Daily data availability: showing 
         - measurements contributed by newly recruited participants (green)
         - measurements from previously enrolled participants (blue)
         - previously enrolled participants without new data (grey, 'lost to follow up').")
```

```{r}
plot_participants <- data_filtered |> 
  filter(!is.na(date)) |> 
  filter(variable == "weight" & group == "overall" & stat == "median") |> 
  dplyr::select(-value) |> 
  mutate(cohort_id_followup = cohort_obs_recorded - cohort_id_new) |> 
  group_by(date, organisation, group, label) |> 
  pivot_longer(cols = c("cohort_obs_missing",
                        "cohort_id_new",
                        "cohort_id_followup")) |> 
  mutate(Participant = fct_rev(fct_recode(name,
                                    "Lost to follow up"="cohort_obs_missing",
                                          "New"="cohort_id_new", 
                                          "Repeated"="cohort_id_followup"))) |> 
  ggplot(aes(x = date)) +
  geom_col(aes(y = value, 
               fill = Participant, alpha = Participant)) +
  labs(x = NULL, y = "Participant data")
ggplotly(plot_participants)
```

