```{r, include=FALSE}
# Filter all data to relevant demographic strata
if (is.na(meta_params$strata) | length(meta_params$strata) > 1) {
  meta_params$strata <- "overall"}

plot_data_timeseries <- org_summary$data$daily_records |> 
  filter(strata == meta_params$strata)

plot_data_latest <- org_summary$data$latest_records |> 
  filter(strata == meta_params$strata)

```

#####

```{r}
#| title: "Current summary"
#| fig-align: center
plot_current_summary_stats(
  plot_data_latest,
  strata = meta_params$strata) |> 
  ggplotly()
```

#####

```{r}
#| title: "Recent trends"
plot_time_series_statistics(
      plot_data = plot_data_timeseries,
      strata = meta_params$strata
    )
```

#####

```{r}
#| title: "BMI category, % weekly participants"
#| fig-align: center
plot_bmicategory_proportions_time_series(plot_data = plot_data_timeseries) |> 
  ggplotly()
```
```{r}
plot_participants_over_time(plot_data_timeseries, 
                            strata = meta_params$strata) |> 
  ggplotly()
```
