
####

```{r}
#| title: "Participant characteristics at baseline"
summary_tables_org$demographic
```

####

```{r}
#| title: "Data quality"
# log$factor_count |> 
#   mutate(p = round(p*100, digits=0)) |> 
#   filter(f %in% c("Missing", "anomaly")) |> 
#          variable = stringr::str_to_sentence(variable),
#          variable = case_when(variable == "Agegroup"~ "Age",
#                               variable == "Children_feeding"~"Dependent children",
#                               variable == "Bmi_category_daily"~"BMI category, current",
#                               variable == "Bmi_category_prewar"~
#                                 "BMI category, autumn 2023",
#                               variable == "Weight_anomaly"~"Weight",
#                               TRUE~variable)) |> 
#   rename("Group" = variable, 
#          "Participant record status" = f, 
#          "Count" = n, 
#          "% all records" = p) |> 
#   kableExtra::kable() |> 
#   kableExtra::add_footnote("Valid ranges: weight, 30-180kg; BMI, 10-60; age, 16-99 years; dependent children, 0-20")
summary_tables_org$data_quality
```
