::: {.panel-accordion}
### Current BMI compared to pre-war

```{r}
#| fig-subcap: "<details><summary>About the data</summary>The percentage of participants by BMI classification^[Body Mass Index: a standardised measure of weight-for-height, in kilograms per metre squared]. Showing all participants' pre-war BMI^[Calculated from estimated weight in October 2023, self-reported at study enrollment], and the most recent ('current') measurement from each participant since the study began in July 2025. Underweight BMI classification (<18.5kg/m2) shown in yellow; with light to dark green, showing normal weight range (18.5-24.9kg/m2), overweight (25 to 29.9kg/m2), and obese (over 30kg/m2) classifications.</details>"
#| fill: false
plot_data_latest <- org_summary$data$latest |> 
  filter(strata == tolower(meta_params$strata)) |> 
  filter(!grepl("(o|O)ther", Stratum)) |> 
  mutate(Stratum = fct_drop(Stratum))

plot_bmi_categories(plot_data = plot_data_latest) |> 
  ggplotly(tooltip = c("fill", "y", "x")) |> 
  layout(legend = list(orientation = "h"))
```

### Weekly change in BMI

```{r}
#| fig-subcap: "<details><summary>About the data</summary>The percentage of participants each week by BMI classification^[Body Mass Index: a standardised measure of weight-for-height, in kilograms per metre squared]. Colour intensity shows number of participants measured each week. Underweight BMI classification (<18.5kg/m2) shown in yellow; with light to dark green, showing normal weight range (18.5-24.9kg/m2), overweight (25 to 29.9kg/m2), and obese (over 30kg/m2) classifications.</details>"
#| fill: false
plot_data_timeseries <- org_summary$data$timeseries |> 
  filter(strata == tolower(meta_params$strata)) |> 
  mutate(across(contains("stratum"), ~ fct_recode(., NULL = "Other")))

plot_weekly_bmi_categories(plot_data = plot_data_timeseries) |> 
  ggplotly(tooltip = c("fill", "y", "alpha")) |> 
  layout(legend = list(orientation = "h"))
```

### Weekly change compared to pre-war {.open}

```{r}
#| fig-subcap: "<details><summary>About the data</summary>The difference between participants' weekly weight^[The latest measurement within the week for each participant], compared to their pre-war weight^[Estimated weight in October 2023, self-reported at study enrollment]. Showing the typical range among participants each week: the median (point) and 25-75% range (IQR; linebar). Colour intensity shows number of participants measured each week.</details>"
#| fill: false

plot_weekly_percentage_change(plot_data = plot_data_timeseries) |> 
  ggplotly() |> 
  layout(legend = list(orientation = 'h'))
```

:::
