---
format: 
  dashboard:
    orientation: columns
    scrolling: false
    css: "styles.css"
    fig-format: svg
toc: false
execute: 
  echo: false
  cache: false
---

```{r, include=FALSE}
# Set up template page per organisation
if (is.na(meta_params$organisation) | length(meta_params$organisation) > 1) {
  meta_params$organisation <- "Overall"}
org_summary <- list()
# Filter data to organisation
org_summary$data <- map(summary$data,
                   ~ .x |> filter(organisation == meta_params$organisation))
# --- print-ready tables
org_summary$tables <- summary$tables[[meta_params$organisation]]
```

## ROW OF TABS {.tabset}

### Key insights

{{< include ./quarto/_tab-key-insights.qmd >}}

<!--- new tab ------------------------------------------------------------>
### Trends by demographic {.tabset}

#### Overall

```{r, include=FALSE}
meta_params$strata <- "overall"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Sex

```{r, include=FALSE}
meta_params$strata <- "sex"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Age

```{r, include=FALSE}
meta_params$strata <- "age"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Dependent children

```{r, include=FALSE}
meta_params$strata <- "children_feeding"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Role

```{r, include=FALSE}
meta_params$strata <- "role"
```

{{< include ./quarto/_tab-demographic.qmd >}}

#### Governorate

```{r, include=FALSE}
meta_params$strata <- "governorate"
```

{{< include ./quarto/_tab-demographic.qmd >}}

<!--- new tab ------------------------------------------------------------>
### Participation

{{< include ./quarto/_tab-participation.qmd >}}

