name: PR Preview

on:
  pull_request:
    branches: [ main ]

# Allow only one concurrent deployment per PR
concurrency:
  group: "pages-${{ github.event.number }}"
  cancel-in-progress: true

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write

    environment:
      name: github-pages-preview
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages Preview
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview deployed!**
              
              Preview URL: ${{ steps.deployment.outputs.page_url }}
              
              This preview will be updated automatically when you push new commits to this PR.`
            })
