name: Quarto Publish

on: workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libeigen3-dev libsuitesparse-dev libcurl4-openssl-dev libfontconfig1-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render site
        run: quarto render

      - name: Upload website
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: site
          retention-days: 5
          path: _site

      - name: Deploy to GitHub pages 🚀
        if: github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
          clean: true
