name: Quarto Preview

on:
  workflow_dispatch:
  pull_request:
    paths:
      - './R/sandbox/pr-test-trigger.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Get branch name
        run: echo "Branch is ${{ github.head_ref }}"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:
            any::knitr,
            any::quarto,
            local::.

      - name: Create simulated data
        run: source(here::here("R", "sandbox", "gaza_adult_wt_sim.R")
        shell: Rscript {0}

      - name: Run data pipeline
        run: source(here::here("R", "data-pipeline", "run-data-pipeline.R")
        shell: Rscript {0}
  
      - name: Render site
        run: quarto render

      - name: Upload website
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: site
          retention-days: 5
          path: _site
    
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.8
        with:
          source-dir: ./_site/
