# Workflow to run the full data pipeline through rendering the website using simulated data
name: Test data pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - './R/data-pipeline/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          use-public-rspm: true

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Create simulated data
        run: Rscript -e 'source(here::here("R", "sandbox", "gaza_adult_wt_sim.R"))'

      - name: Run data pipeline
        run: Rscript -e 'source(here::here("R", "data-pipeline", "run-public-pipeline.R"))'

      - name: Print log
        run: Rscript -e 'print(readRDS(here::here("data", "public", "log.RDS")))'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.8
        with:
          source-dir: ./_site/
