name: Test pipeline

on:
  workflow_dispatch:
  pull_request:
    paths:
      - './R/sandbox/pr-test-trigger.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
           cache-version: 1

      - name: Create simulated data
        run: source(here::here("R", "sandbox", "gaza_adult_wt_sim.R")
        shell: Rscript {0}

      - name: Run data pipeline
        run: source(here::here("R", "data-pipeline", "run-data-pipeline.R")
        shell: Rscript {0}

      - name: Print log
        run: print(readRDS(here::here("data", "public", "log.RDS")))
        shell: Rscript {0}
    
